'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const migrations=read('electron/migrations.js'), queries=read('electron/queries.js'), preload=read('electron/preload.js'), main=read('electron/main.js'), ui=read('src/screens/DocumentsScreen.jsx');
assert.match(migrations,/version:\s*14/);
assert.match(migrations,/converted_credit_sale_id/);
assert.match(migrations,/source_document_id/);
assert.match(queries,/convertProformaToCreditSale/);
assert.match(queries,/completeCreditSale\(/);
assert.match(queries,/createCreditInvoiceTx/);
assert.match(queries,/allocateDocumentDiscount/);
assert.doesNotMatch(queries,/PROFORMA_TAX_DISCOUNT_CONVERSION_NOT_SUPPORTED/);
assert.match(queries,/UPDATE invoices SET amount_paid=\?,status=\?/);
assert.match(preload,/convertProformaToCreditSale/);
assert.match(main,/commercialDocuments:convertToCreditSale/);
assert.match(ui,/Credit Sale \+ Invoice/);
assert.match(ui,/Invoice Register/);
console.log('b2b transaction conversion contract passed');
