const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const q=fs.readFileSync(path.join(root,'electron','queries.js'),'utf8');
const m=fs.readFileSync(path.join(root,'electron','migrations.js'),'utf8');
const invoice=fs.readFileSync(path.join(root,'src','components','InvoiceModal.jsx'),'utf8');
assert(m.includes("version: 16"),'migration 16 missing');
assert(m.includes('CREATE TABLE IF NOT EXISTS tax_ledger'),'tax ledger missing');
assert(m.includes("add('subtotal'"),'invoice subtotal missing');
assert(m.includes("add('discount'"),'invoice discount missing');
assert(m.includes("add('tax'"),'invoice tax missing');
assert(m.includes("add('tax_rate'"),'invoice tax rate missing');
assert(q.includes('allocateDocumentDiscount'),'discount allocation helper missing');
assert(q.includes('applyDocumentFinancialsToInvoice'),'invoice financial bridge missing');
assert(q.includes("UPDATE credit_sales SET total_amount=?"),'credit receivable does not include tax');
assert(!q.includes('PROFORMA_TAX_DISCOUNT_CONVERSION_NOT_SUPPORTED'),'old conversion block remains');
assert(q.includes('getTaxSummary'),'tax summary missing');
assert(invoice.includes('invoice.tax'),'invoice does not render persisted tax');
assert(invoice.includes('invoice.discount'),'invoice does not render persisted discount');
console.log('PASS b2b tax/discount accounting contract');
