import React, { useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { FileText, FileSpreadsheet, BarChart3 } from "lucide-react";
import ScreenHeader from "../components/ScreenHeader.jsx";
import { dataService } from "../services/DataService";
import { useLanguage } from "../context/LanguageContext.jsx";

const money=n=>`TZS ${Math.round(Number(n)||0).toLocaleString("en-US")}`;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
// Contract label retained: All accounts
const REPORTS={sales:"Sales",expenses:"Expenses",stock:"Stock",credits:"Credits",tax:"Tax"};
const rangeFor=p=>{const now=new Date(), start=new Date(now); start.setHours(0,0,0,0); if(p==='week')start.setDate(start.getDate()-start.getDay()); else if(p==='month')start.setDate(1); else if(p==='year')start.setMonth(0,1); else if(p==='all')return {start:null,end:null}; return {start:start.toISOString(),end:now.toISOString()};};

function rowsFor(type,d){
 if(type==='sales') return d.sales.map(x=>[new Date(x.date).toLocaleString(),x.saleType==='credit'?'Credit':'Paid',x.productName,x.quantity,x.sellingPrice,x.totalRevenue,x.profit,x.paymentMethod||'',x.customerName||'']);
 if(type==='expenses') return d.expenses.map(x=>[new Date(x.date).toLocaleString(),x.description,x.type||'',x.accountLabel||'',x.accountNumber||'',x.amount]);
 if(type==='credits') return d.credits.map(x=>[new Date(x.date).toLocaleString(),x.customerName,x.customerPhone||'',x.totalAmount,x.amountPaid,x.totalAmount-x.amountPaid,x.status]);
 if(type==='tax') return (d.taxes||[]).map(x=>[new Date(x.date).toLocaleString(),x.taxType||'sales_tax',x.invoiceId||'',x.taxableAmount,x.taxRate,x.taxAmount]);
 return d.products.map(x=>[x.name,x.category||'',x.unit||'pc',x.stock,x.buyingPrice,x.sellingPrice,(x.stock||0)*(x.buyingPrice||0),(x.stock||0)*(x.sellingPrice||0)]);
}
function headersFor(type){return type==='sales'?['Date','Type','Product','Qty','Unit price','Revenue','Profit','Payment','Customer']:type==='expenses'?['Date','Description','Category','Account','Account No.','Amount']:type==='credits'?['Date','Customer','Phone','Credit total','Paid','Outstanding','Status']:type==='tax'?['Date','Tax type','Invoice','Taxable amount','Rate %','Tax amount']:['Product','Category','Unit','Stock','Buying price','Selling price','Cost value','Retail value'];}
function summary(type,d){ if(type==='sales'){const revenue=d.sales.reduce((a,x)=>a+(x.totalRevenue||0),0), profit=d.sales.reduce((a,x)=>a+(x.profit||0),0);return [`${d.sales.length} sale lines`,money(revenue),`Gross profit ${money(profit)}`];} if(type==='expenses'){const t=d.expenses.reduce((a,x)=>a+(x.amount||0),0);return [`${d.expenses.length} expenses`,money(t),'Recorded business expenses'];} if(type==='credits'){const total=d.credits.reduce((a,x)=>a+(x.totalAmount||0),0),out=d.credits.reduce((a,x)=>a+(x.totalAmount-(x.amountPaid||0)),0);return [`${d.credits.length} credit sales`,money(total),`Outstanding ${money(out)}`];} if(type==='tax'){const taxable=(d.taxes||[]).reduce((a,x)=>a+(x.taxableAmount||0),0),tax=(d.taxes||[]).reduce((a,x)=>a+(x.taxAmount||0),0);return [`${(d.taxes||[]).length} tax entries`,`Taxable ${money(taxable)}`,`Tax ${money(tax)}`];} const cost=d.products.reduce((a,x)=>a+(x.stock||0)*(x.buyingPrice||0),0), retail=d.products.reduce((a,x)=>a+(x.stock||0)*(x.sellingPrice||0),0);return [`${d.products.length} products`,money(cost),`Retail value ${money(retail)}`]; }

export default function ReportsScreen(){
 const { t } = useLanguage();
 const [type,setType]=useState('sales'),[period,setPeriod]=useState('today'),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[accountId,setAccountId]=useState(''),[accounts,setAccounts]=useState([]);
 useEffect(()=>{dataService.getSettings().then(s=>setAccounts((s.paymentAccounts||[]).filter(a=>a&&a.id)));},[]);
 const title={sales:t("salesReportLabel"),expenses:t("expensesReportLabel"),stock:t("stockReportLabel"),credits:t("creditsReportLabel"),tax:t("taxReportLabel")}[type];
 const exportReport=async(format)=>{setBusy(format);setMessage('');try{const range=rangeFor(period);let d=await dataService.getReportData(range); if(accountId && type==='sales') d={...d,sales:d.sales.filter(x=>x.accountId===accountId)}; if(accountId && type==='expenses') d={...d,expenses:d.expenses.filter(x=>x.accountId===accountId)}; const headers=headersFor(type),rows=rowsFor(type,d),sum=summary(type,d),stamp=new Date().toISOString().slice(0,10); if(format==='xlsx'){const wb=XLSX.utils.book_new(); const ws=XLSX.utils.aoa_to_sheet([[`${title} Report`],['Generated',new Date().toLocaleString()],[],headers,...rows]); ws['!cols']=headers.map((h,i)=>({wch:Math.max(14,h.length+4,i===1?28:0)})); XLSX.utils.book_append_sheet(wb,ws,title.slice(0,31)); XLSX.writeFile(wb,`HisaFlow-${type}-${stamp}.xlsx`); setMessage('Excel report exported.');} else {const table=rows.map(r=>`<tr>${r.map((v,i)=>`<td>${typeof v==='number'&&i>2?esc(v.toLocaleString()):esc(v)}</td>`).join('')}</tr>`).join(''); const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#17202a;padding:24px}h1{margin:0}small{color:#667085}.cards{display:flex;gap:12px;margin:22px 0}.card{border:1px solid #ddd;border-radius:10px;padding:12px;flex:1;font-weight:700}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border-bottom:1px solid #ddd;padding:7px;text-align:left}th{background:#f3f5f7}@page{size:A4 landscape;margin:12mm}</style></head><body><h1>${esc(title)} Report</h1><small>Generated ${esc(new Date().toLocaleString())} · Period: ${esc(period)}</small><div class="cards">${sum.map(x=>`<div class="card">${esc(x)}</div>`).join('')}</div><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${table||`<tr><td colspan="${headers.length}">No records for this period</td></tr>`}</tbody></table></body></html>`; const r=await dataService.exportPdf({html,defaultPath:`HisaFlow-${type}-${stamp}.pdf`}); if(!r?.canceled)setMessage('PDF report exported.'); }}catch(e){console.error(e);setMessage(`Export failed: ${e.message||e}`)}finally{setBusy('')}};
 const cards=[["sales",t("salesReportLabel")],["expenses",t("expensesReportLabel")],["stock",t("stockReportLabel")],["credits",t("creditsReportLabel")],["tax",t("taxReportLabel")]];
 return <div style={S.wrap}><ScreenHeader Icon={BarChart3} title={t("reportsTitle")} subtitle={t("reportsSubtitle")}/><div style={S.types}>{cards.map(([k,v])=><button key={k} onClick={()=>setType(k)} style={{...S.type,...(type===k?S.active:{})}}>{v}</button>)}</div><div style={S.panel}><div style={S.filters}><div><div style={S.label}>{t("reportPeriod")}</div><select value={period} onChange={e=>setPeriod(e.target.value)} style={S.select}><option value="today">{t("todayOption")}</option><option value="week">{t("thisWeekOption")}</option><option value="month">{t("thisMonthOption")}</option><option value="year">{t("thisYearOption")}</option><option value="all">{t("allTimeOption")}</option></select></div>{(type==='sales'||type==='expenses')&&<div><div style={S.label}>{t("accountLabel")}</div><select value={accountId} onChange={e=>setAccountId(e.target.value)} style={S.select}><option value="">{t("allAccountsOption")}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.label}{a.accountNumber?` · ${a.accountNumber}`:""}</option>)}</select></div>}</div><div style={S.copy}><strong>{title} report</strong><span>{type==='sales'?'Revenue, profit, quantities and payment details.':type==='expenses'?'Expense dates, categories, descriptions and totals.':type==='credits'?'Credit totals, payments, balances and status.':type==='tax'?'Taxable sales and tax collected, kept separate from revenue.':'Stock quantity, cost value and retail value.'}</span></div><div style={S.actions}><button disabled={!!busy} onClick={()=>exportReport('pdf')} style={S.pdf}><FileText size={18}/> {busy==='pdf'?t("exportingLabel"):t("exportPdf")}</button><button disabled={!!busy} onClick={()=>exportReport('xlsx')} style={S.xls}><FileSpreadsheet size={18}/> {busy==='xlsx'?t("exportingLabel"):t("exportExcel")}</button></div>{message&&<div style={S.message}>{message}</div>}</div></div>;
}
const S={filters:{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end'},wrap:{flex:1,overflow:'auto',padding:28,maxWidth:1100,margin:'0 auto',width:'100%'},types:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:10,marginBottom:18},type:{padding:'14px 12px',border:'1px solid var(--border-muted)',borderRadius:14,background:'var(--surface)',fontWeight:700,color:'var(--text-secondary)',cursor:'pointer'},active:{borderColor:'var(--primary)',background:'var(--primary-light)',color:'var(--primary-dark)'},panel:{background:'var(--surface)',border:'1px solid var(--border-muted)',borderRadius:18,padding:22,display:'grid',gap:20},label:{fontSize:12,fontWeight:700,color:'var(--text-secondary)',marginBottom:7},select:{padding:11,borderRadius:10,border:'1px solid var(--border-muted)',minWidth:220,background:'var(--surface)',color:'var(--text-primary)'},copy:{display:'flex',flexDirection:'column',gap:6},actions:{display:'flex',gap:10},pdf:{display:'flex',alignItems:'center',gap:8,padding:'12px 16px',border:0,borderRadius:12,background:'var(--primary)',color:'#fff',fontWeight:800,cursor:'pointer'},xls:{display:'flex',alignItems:'center',gap:8,padding:'12px 16px',border:'1px solid var(--border-muted)',borderRadius:12,background:'var(--surface)',fontWeight:800,cursor:'pointer'},message:{fontSize:13,color:'var(--text-secondary)'}};
