const {createCommandGuard}=require('./commandGuard');
function createCreditService({inventory,repositories,transactionRunner,idFactory,clock=()=>new Date().toISOString()}){
 const guard=createCommandGuard(repositories.receipts);
 function complete(request){return guard(request.operationId,'credit.completeSale',request,()=>{const items=Array.isArray(request.cartItems)?request.cartItems:[];if(!items.length)throw new Error('EMPTY_CREDIT_CART');const customerName=String(request.customerName||'').trim();if(!customerName)throw new Error('CUSTOMER_REQUIRED');if(request.orderId){const o=repositories.orders.findStatus(request.orderId);if(!o)throw new Error('ORDER_NOT_FOUND');if(o.status!=='pending')throw new Error('ORDER_CLOSED');}
  const date=clock(),creditSaleId=idFactory('cs');let totalAmount=0;const lines=[];for(const item of items){const quantity=Number(item.quantity),sellingPrice=Number(item.sellingPrice);if(!(quantity>0))throw new Error('INVALID_CREDIT_QUANTITY');if(!(sellingPrice>0))throw new Error('INVALID_CREDIT_PRICE');const p=repositories.products.findById(item.productId);if(!p)throw new Error('PRODUCT_NOT_FOUND');let c;try{c=inventory.consumeFIFO(item.productId,quantity,{now:date,movementType:'SALE',referenceType:'credit_sale',referenceId:creditSaleId,actorName:request.actorName||null});}catch(err){if(err.message==='INSUFFICIENT_STOCK'){const e=new Error('INSUFFICIENT_STOCK');e.available=err.available;e.productName=p.name;throw e;}throw err;}totalAmount+=quantity*sellingPrice;lines.push({id:idFactory('cci'),product:p,productId:p.id,productName:p.name,quantity,sellingPrice,costAtSale:c.effectiveBuyingPrice,batchBreakdown:c.breakdown});}
  repositories.credit.insertSale({id:creditSaleId,customerName,customerPhone:String(request.customerPhone||'').trim(),totalAmount,date,actorName:request.actorName||null});for(const l of lines)repositories.credit.insertItem({...l,creditSaleId,productCategory:l.product.category,productBrand:l.product.brand,productUnit:l.product.unit,productImageUri:l.product.image_uri,productSize:l.product.size,date});if(request.orderId)repositories.orders.markFulfilled(request.orderId,date);repositories.activities.append({id:idFactory('al'),action:'sold on credit',details:`${customerName} — TZS ${Math.round(totalAmount).toLocaleString('en-US')}`,actorName:request.actorName||null,date});return{id:creditSaleId,customerName,customerPhone:String(request.customerPhone||'').trim(),totalAmount,amountPaid:0,status:'pending',date,actorName:request.actorName||null,items:lines.map(l=>({productId:l.productId,productName:l.productName,quantity:l.quantity,sellingPrice:l.sellingPrice,costAtSale:l.costAtSale,batchBreakdown:l.batchBreakdown}))};});}
 function payment(request){return guard(request.operationId,'credit.recordPayment',request,()=>{const amount=Number(request.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('INVALID_PAYMENT_AMOUNT');const cs=repositories.credit.findById(request.creditSaleId);if(!cs)throw new Error('CREDIT_NOT_FOUND');const remaining=Number(cs.total_amount)-Number(cs.amount_paid);if(amount>remaining+1e-9){const e=new Error('PAYMENT_EXCEEDS_BALANCE');e.remaining=remaining;throw e;}const paid=Number(cs.amount_paid)+amount,status=paid>=Number(cs.total_amount)-1e-9?'paid':'partial',date=clock(),paymentId=idFactory('ccp');repositories.credit.updatePaymentState(cs.id,paid,status,date);repositories.credit.insertPayment({id:paymentId,creditSaleId:cs.id,amount,paymentMethod:request.paymentMethod||'',accountId:request.accountId||null,accountLabel:request.accountLabel||'',accountNumber:request.accountNumber||'',date});repositories.accountLedger?.record({id:idFactory('alg'),accountId:request.accountId||null,accountLabel:request.accountLabel||'',accountNumber:request.accountNumber||'',direction:'in',amount,entryType:'credit_payment',referenceType:'credit_payment',referenceId:paymentId,description:`Credit payment: ${cs.customer_name}`,date});repositories.activities.append({id:idFactory('al'),action:'recorded a credit payment',details:`${cs.customer_name} — TZS ${Math.round(amount).toLocaleString('en-US')}`,actorName:request.actorName||null,date});return{paymentId,status,amountPaid:paid,remaining:Math.max(0,Number(cs.total_amount)-paid)};});}
 function remove(request){return guard(request.operationId,'credit.delete',request,()=>{const cs=repositories.credit.findById(request.creditSaleId);if(!cs)throw new Error('CREDIT_NOT_FOUND');const items=repositories.credit.listItems(cs.id),date=clock();for(const item of items){const p=repositories.products.findById(item.product_id);if(!p)continue;let breakdown=null;try{breakdown=item.batch_breakdown?JSON.parse(item.batch_breakdown):null;}catch{}inventory.restoreConsumption({productId:item.product_id,breakdown,totalQuantity:item.quantity,fallbackBuyingPrice:item.cost_at_sale??p.buying_price??0,fallbackDate:date,idFactory,movementType:'RETURN',referenceType:'credit_sale_delete',referenceId:cs.id,actorName:request.actorName||null});}repositories.credit.deleteById(cs.id);repositories.activities.append({id:idFactory('al'),action:'deleted a credit sale',details:`${cs.customer_name} — TZS ${Math.round(cs.total_amount).toLocaleString('en-US')}`,actorName:request.actorName||null,date});return{deleted:true,creditSaleId:cs.id};});}
 return{completeTx:r=>transactionRunner.run(()=>complete(r)),paymentTx:r=>transactionRunner.run(()=>payment(r)),deleteTx:r=>transactionRunner.run(()=>remove(r))};
}
module.exports={createCreditService};
