const {createCommandGuard}=require('./commandGuard');
function createPurchaseService({inventory,repositories,transactionRunner,idFactory,clock=()=>new Date().toISOString()}){
 const guard=createCommandGuard(repositories.receipts);
 function validate(item){const quantity=Number(item.quantity),buyingPrice=Number(item.buyingPrice);if(!Number.isFinite(quantity)||quantity<=0)throw new Error('INVALID_PURCHASE_QUANTITY');if(!Number.isFinite(buyingPrice)||buyingPrice<0)throw new Error('INVALID_PURCHASE_PRICE');const p=repositories.products.findById(item.productId);if(!p)throw new Error('PRODUCT_NOT_FOUND');return{quantity,buyingPrice,p};}
 function line(item,meta,date){const v=validate(item),id=idFactory('b');inventory.receiveStock({batchId:id,productId:item.productId,quantity:v.quantity,buyingPrice:v.buyingPrice,date,supplierId:meta.supplierId||null,supplierName:meta.supplierName||null,paymentMethod:meta.paymentMethod||null,accountId:meta.accountId||null,accountLabel:meta.accountLabel||null,accountNumber:meta.accountNumber||null,movementType:'PURCHASE',referenceType:'purchase',referenceId:meta.operationId||id,actorName:meta.actorName||null,metadata:{supplierId:meta.supplierId||null}});repositories.accountLedger?.record({id:idFactory('alg'),accountId:meta.accountId||null,accountLabel:meta.accountLabel||'',accountNumber:meta.accountNumber||'',direction:'out',amount:v.quantity*v.buyingPrice,entryType:'stock_purchase',referenceType:'stock_batch',referenceId:id,description:`Stock: ${v.p.name}`,date});return{batchId:id,productId:item.productId,productName:v.p.name,quantity:v.quantity,buyingPrice:v.buyingPrice};}
 function add(request){return guard(request.operationId,'purchase.addStock',request,()=>{const date=clock(),l=line(request,request,date);repositories.activities.append({id:idFactory('al'),action:'added stock',details:`${l.productName} +${l.quantity} @ TZS ${Math.round(l.buyingPrice).toLocaleString('en-US')}`,actorName:request.actorName||null,date});return l;});}
 function cart(items,meta={}){return guard(meta.operationId,'purchase.completeCart',{items,meta},()=>{if(!Array.isArray(items)||!items.length)throw new Error('EMPTY_PURCHASE_CART');const date=clock(),lines=items.map(i=>line(i,meta,date));repositories.activities.append({id:idFactory('al'),action:'restocked multiple products',details:`${lines.length} bidhaa${meta.accountLabel?` — ${meta.accountLabel}`:''}`,actorName:meta.actorName||null,date});return lines;});}
 return{addTx:r=>transactionRunner.run(()=>add(r)),cartTx:(i,m)=>transactionRunner.run(()=>cart(i,m))};
}
module.exports={createPurchaseService};
