const { requestHash, createCommandGuard } = require('./commandGuard');
class SalesDomainError extends Error {}
function createSalesService({ inventory, repositories, transactionRunner, idFactory, clock=()=>new Date().toISOString() }) {
  const guard=createCommandGuard(repositories.receipts);
  function validateLine(item){const q=Number(item.quantity),price=Number(item.sellingPrice),discount=Number(item.discount||0);if(!Number.isFinite(q)||q<=0)throw new SalesDomainError(`${item.productName||'Bidhaa'}: weka kiasi sahihi`);if(!Number.isFinite(price)||price<=0)throw new SalesDomainError(`${item.productName||'Bidhaa'}: weka bei sahihi ya kuuza`);if(!Number.isFinite(discount)||discount<0)throw new SalesDomainError(`${item.productName||'Bidhaa'}: punguzo haliwezi kuwa hasi`);if(discount>=price*q)throw new SalesDomainError(`${item.productName||'Bidhaa'}: punguzo haliwezi kuzidi bei ya jumla`);return{quantity:q,sellingPrice:price,discount};}
  function sellLine(item,meta,date){const v=validateLine(item),p=repositories.products.findById(item.productId);if(!p)throw new SalesDomainError(`${item.productName||'Bidhaa'} haipatikani tena`);const saleId=idFactory('s');let c;try{c=inventory.consumeFIFO(item.productId,v.quantity,{now:date,movementType: 'SALE', referenceType: 'sale', referenceId: saleId,actorName:meta.actorName||null});}catch(err){if(err.message==='INSUFFICIENT_STOCK')throw new SalesDomainError(`${p.name}: stoo haitoshi (${err.available} pekee zimebaki)`);throw err;}const totalRevenue=v.sellingPrice*v.quantity-v.discount;const sale={id:saleId,productId:item.productId,productName:p.name,quantity:v.quantity,buyingPrice:c.effectiveBuyingPrice,sellingPrice:v.sellingPrice,totalCost:c.totalCost,totalRevenue,profit:totalRevenue-c.totalCost,paymentMethod:meta.paymentMethod||'cash',accountId:meta.accountId||null,accountLabel:meta.accountLabel||'',accountNumber:meta.accountNumber||'',notes:'',date,batchBreakdown:c.breakdown,customerPhone:meta.customerPhone||null,customerName:meta.customerName||null,discount:v.discount,productCategory:p.category||null,productBrand:p.brand||null,productUnit:p.unit||null,productImageUri:p.image_uri||null,productSize:p.size||null,actorName:meta.actorName||null};repositories.sales.insert(sale);repositories.accountLedger?.record({id:idFactory('alg'),accountId:sale.accountId,accountLabel:sale.accountLabel,accountNumber:sale.accountNumber,direction:'in',amount:totalRevenue,entryType:'sale',referenceType:'sale',referenceId:saleId,description:`Sale: ${p.name}`,date});return sale;}
  function completeSingle(request){return guard(request.operationId,'sale.complete',request,()=>{const date=clock(),sale=sellLine(request,request,date);repositories.activities.append({id:idFactory('al'),action:'sold a product',details:`${sale.productName} × ${sale.quantity} — TZS ${Math.round(sale.totalRevenue).toLocaleString('en-US')}`,actorName:request.actorName||null,date});return sale;});}
  function completeCart(items,meta){return guard(meta.operationId,'sale.completeCart',{items,meta},()=>{if(!items.length)throw new SalesDomainError('Hakuna bidhaa kwenye kikapu');const date=clock();if(meta.orderId){const order=repositories.orders.findStatus(meta.orderId);if(!order)throw new SalesDomainError('Oda haipatikani');if(order.status!=='pending')throw new SalesDomainError('Oda tayari imefungwa');}const sales=items.map(i=>sellLine(i,meta,date));if(meta.orderId)repositories.orders.markFulfilled(meta.orderId,date);const total=sales.reduce((sum,s)=>sum+s.totalRevenue,0);repositories.activities.append({id:idFactory('al'),action:'sold multiple products',details:`${sales.length} bidhaa — TZS ${Math.round(total).toLocaleString('en-US')}`,actorName:meta.actorName||null,date});return sales;});}
  return { completeSingleTx:(request)=>transactionRunner.run(()=>completeSingle(request)), completeCartTx:(items,meta)=>transactionRunner.run(()=>completeCart(items,meta)) };
}
module.exports={createSalesService,SalesDomainError,requestHash};
